# Generated by Django 3.1.1 on 2020-09-15 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Treasury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tenor_1M', models.DecimalField(decimal_places=9, max_digits=10)),
                ('tenor_2M', models.DecimalField(decimal_places=9, max_digits=10)),
                ('tenor_3M', models.DecimalField(decimal_places=9, max_digits=10)),
                ('tenor_6M', models.DecimalField(decimal_places=9, max_digits=10)),
                ('tenor_1Y', models.DecimalField(decimal_places=9, max_digits=10)),
                ('tenor_2Y', models.DecimalField(decimal_places=9, max_digits=10)),
                ('tenor_3Y', models.DecimalField(decimal_places=9, max_digits=10)),
                ('tenor_5Y', models.DecimalField(decimal_places=9, max_digits=10)),
                ('tenor_7Y', models.DecimalField(decimal_places=9, max_digits=10)),
                ('tenor_10Y', models.DecimalField(decimal_places=9, max_digits=10)),
                ('tenor_20Y', models.DecimalField(decimal_places=9, max_digits=10)),
                ('tenor_30Y', models.DecimalField(decimal_places=9, max_digits=10)),
            ],
        ),
    ]
